# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :macos, '10.14'

install! 'cocoapods', :disable_input_output_paths => true
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'HappyCodableDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'HappyCodable/Common', :path => '../Source'
end

target 'HappyCodableCommandLine' do
	pod 'HappyCodable/CommandLine', :path => '../Source'
end

target 'CommandLineTests' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
	
	pod 'HappyCodable/CommandLine', :path => '../Source'
end

target 'CommonTests' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!
	
	pod 'HappyCodable/Common', :path => '../Source'
end
