# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :macos, '10.14'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'Demo' do
	pod 'HappyCodable', :path => '../Source'
end

target 'DemoTests' do
	pod 'HappyCodable', :path => '../Source'
end
